Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Internal Server Error: /d3_test/
Traceback (most recent call last):
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sinto\Documents\PycharmProjects\MyBudget\appsetup\budget\views.py", line 145, in show_d3
    raise Exception('Make response code 500!')
Exception: Make response code 500!
Internal Server Error: /d3_test/
Traceback (most recent call last):
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sinto\Documents\PycharmProjects\MyBudget\appsetup\budget\views.py", line 145, in show_d3
    raise Exception('Make response code 500!')
Exception: Make response code 500!
"GET /d3_test/ HTTP/1.1" 500 118765
"GET /d3_test/ HTTP/1.1" 500 118765
Internal Server Error: /d3_test/
Traceback (most recent call last):
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sinto\Documents\PycharmProjects\MyBudget\appsetup\budget\views.py", line 145, in show_d3
    raise Exception('Make response code 500!')
Exception: Make response code 500!
Internal Server Error: /d3_test/
Traceback (most recent call last):
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sinto\Documents\PycharmProjects\MyBudget\appsetup\budget\views.py", line 145, in show_d3
    raise Exception('Make response code 500!')
Exception: Make response code 500!
"GET /d3_test/ HTTP/1.1" 500 118893
"GET /d3_test/ HTTP/1.1" 500 118893
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2476
Internal Server Error: /d3_test/
Traceback (most recent call last):
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sinto\Documents\PycharmProjects\MyBudget\appsetup\budget\views.py", line 145, in show_d3
    raise Exception('Make response code 500!')
Exception: Make response code 500!
Internal Server Error: /d3_test/
Traceback (most recent call last):
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Sinto\Documents\PycharmProjects\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sinto\Documents\PycharmProjects\MyBudget\appsetup\budget\views.py", line 145, in show_d3
    raise Exception('Make response code 500!')
Exception: Make response code 500!
"GET /d3_test/ HTTP/1.1" 500 118765
"GET /d3_test/ HTTP/1.1" 500 118765
